### ISSUE TITLE
react students login from

### ISSUE THREAD

**Issue by AdamsGeeky** [open-source-learners/comminityink#11]

**Comment by armanvirus** [comment]
We are going to provide a UI for the contractors to have clear view of what there are up to.

**Comment by armanvirus** [comment]
thank you for showing your interest on the project and the community as well.

**Comment by armanvirus** [comment]
Here are png and files of the form
![studoor 2](https://user-images.githubusercontent.com/86750683/194681091-9cd2dce3-9ba4-4c0a-a88d-179ab6a38ab3.png)

**Comment by armanvirus** [comment]
here its figma file as well
https://www.figma.com/file/Lwg33LOi5rING3BRiVm8bP/Untitled?node-id=1%3A14

**Comment by tanitoluwam** [comment]
i would love to work on this task,kindly assign to me

**Comment by armanvirus** [comment]
Ok Go ahead
