### ISSUE TITLE
pomodoro component in react

### ISSUE THREAD

**Issue by AdamsGeeky** [open-source-learners/comminityink#15]

**Comment by 2brownc** [comment]
What is the expected functionality?

- Ability to set the pomodoro time.
- Ability to set break time.
- Ability to set sequence of intervals and break time. Eg: 25 pomodoro, 5 break, 25 pomodoro, 20 break...
- Digital or analog clock?
- Styling?

**Comment by tanitoluwam** [comment]
i would love to work on this, kindly assign to me

**Comment by AdamsGeeky** [comment]
Great you are Good to Go

**Comment by tanitoluwam** [comment]
i think i will need some help, this is my first time doing open source
what exactly am i building... and where,, am i to create a new folder or i am to build it in an existing folder

**Comment by AdamsGeeky** [comment]
As you can see we are using **Docusaurus** is a static-site generator. It builds a single-page application with fast client-side navigation, leveraging the full power of **React** to make your site interactive
the project folder structure is similar to React  for you Task if you clone the project  just Go to **src/component** and Create  the Component name *pomodoro* for move information check (contribution.md and Readme.md in the repo) also check https://docusaurus.io/ for Details

**Comment by AdamsGeeky** [comment]
thanks for you interest even if you are new to react or web you are welcome to learn as we go

**Comment by tanitoluwam** [comment]
okay, i will, thank You

**Comment by AdamsGeeky** [comment]
Good to Go
